version: "3"
services:
  auth:
    image: auth
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "10080:10080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/auth
    networks:
      - webnet
networks:
  webnet: